WITH SUB AS (
        SELECT H.HISTORY_ID, 
               C.CAR_TYPE,
               C.DAILY_FEE,
               DATEDIFF(H.END_DATE, H.START_DATE) AS DIFF,
               CASE
                   WHEN DATEDIFF(H.END_DATE, H.START_DATE) < 6 THEN '0' 
                   WHEN DATEDIFF(H.END_DATE, H.START_DATE) < 29 THEN '7일 이상'
                   WHEN DATEDIFF(H.END_DATE, H.START_DATE) < 89 THEN '30일 이상'
                   ELSE '90일 이상'
               END AS TERM
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
                INNER JOIN CAR_RENTAL_COMPANY_CAR AS C ON H.CAR_ID = C.CAR_ID
        WHERE C.CAR_TYPE = '트럭'
        )


SELECT SUB.HISTORY_ID,
       TRUNCATE(IF(D.DISCOUNT_RATE IS NULL, SUB.DAILY_FEE * (DIFF+1), SUB.DAILY_FEE * (DIFF+1) - (SUB.DAILY_FEE * (DIFF+1) * D.DISCOUNT_RATE / 100)), 0) AS FEE
FROM SUB 
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D ON SUB.CAR_TYPE = D.CAR_TYPE
AND SUB.TERM = D.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC